/* eslint-disable */
// @generated by protobuf-ts 2.9.6 with parameter eslint_disable,output_javascript,output_legacy_commonjs,use_proto_field_name
// @generated from protobuf file "variableForUserParams.proto" (syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message NullableString
 */
export interface NullableString {
    /**
     * @generated from protobuf field: string value = 1;
     */
    value: string;
    /**
     * @generated from protobuf field: bool isNull = 2;
     */
    isNull: boolean;
}
/**
 * @generated from protobuf message NullableDouble
 */
export interface NullableDouble {
    /**
     * @generated from protobuf field: double value = 1;
     */
    value: number;
    /**
     * @generated from protobuf field: bool isNull = 2;
     */
    isNull: boolean;
}
/**
 * @generated from protobuf message CustomDataValue
 */
export interface CustomDataValue {
    /**
     * @generated from protobuf field: CustomDataType type = 1;
     */
    type: CustomDataType;
    /**
     * @generated from protobuf field: optional bool boolValue = 2;
     */
    boolValue?: boolean;
    /**
     * @generated from protobuf field: optional double doubleValue = 3;
     */
    doubleValue?: number;
    /**
     * @generated from protobuf field: optional string stringValue = 4;
     */
    stringValue?: string;
}
/**
 * @generated from protobuf message NullableCustomData
 */
export interface NullableCustomData {
    /**
     * @generated from protobuf field: map<string, CustomDataValue> value = 1;
     */
    value: {
        [key: string]: CustomDataValue;
    };
    /**
     * @generated from protobuf field: bool isNull = 2;
     */
    isNull: boolean;
}
/**
 * @generated from protobuf message VariableForUserParams_PB
 */
export interface VariableForUserParams_PB {
    /**
     * @generated from protobuf field: string sdkKey = 1;
     */
    sdkKey: string;
    /**
     * @generated from protobuf field: string variableKey = 2;
     */
    variableKey: string;
    /**
     * @generated from protobuf field: VariableType_PB variableType = 3;
     */
    variableType: VariableType_PB;
    /**
     * @generated from protobuf field: DVCUser_PB user = 4;
     */
    user?: DVCUser_PB;
    /**
     * @generated from protobuf field: bool shouldTrackEvent = 5;
     */
    shouldTrackEvent: boolean;
}
/**
 * @generated from protobuf message DVCUser_PB
 */
export interface DVCUser_PB {
    /**
     * @generated from protobuf field: string user_id = 1;
     */
    user_id: string;
    /**
     * @generated from protobuf field: NullableString email = 2;
     */
    email?: NullableString;
    /**
     * @generated from protobuf field: NullableString name = 3;
     */
    name?: NullableString;
    /**
     * @generated from protobuf field: NullableString language = 4;
     */
    language?: NullableString;
    /**
     * @generated from protobuf field: NullableString country = 5;
     */
    country?: NullableString;
    /**
     * @generated from protobuf field: NullableDouble appBuild = 6;
     */
    appBuild?: NullableDouble;
    /**
     * @generated from protobuf field: NullableString appVersion = 7;
     */
    appVersion?: NullableString;
    /**
     * @generated from protobuf field: NullableString deviceModel = 8;
     */
    deviceModel?: NullableString;
    /**
     * @generated from protobuf field: NullableCustomData customData = 9;
     */
    customData?: NullableCustomData;
    /**
     * @generated from protobuf field: NullableCustomData privateCustomData = 10;
     */
    privateCustomData?: NullableCustomData;
}
/**
 * @generated from protobuf message SDKVariable_PB
 */
export interface SDKVariable_PB {
    /**
     * @generated from protobuf field: string _id = 1;
     */
    _id: string;
    /**
     * @generated from protobuf field: VariableType_PB type = 2;
     */
    type: VariableType_PB;
    /**
     * @generated from protobuf field: string key = 3;
     */
    key: string;
    /**
     * @generated from protobuf field: bool boolValue = 4;
     */
    boolValue: boolean;
    /**
     * @generated from protobuf field: double doubleValue = 5;
     */
    doubleValue: number;
    /**
     * @generated from protobuf field: string stringValue = 6;
     */
    stringValue: string;
    /**
     * @generated from protobuf field: NullableString evalReason = 7;
     */
    evalReason?: NullableString;
}
/**
 * @generated from protobuf enum VariableType_PB
 */
export declare enum VariableType_PB {
    /**
     * @generated from protobuf enum value: Boolean = 0;
     */
    Boolean = 0,
    /**
     * @generated from protobuf enum value: Number = 1;
     */
    Number = 1,
    /**
     * @generated from protobuf enum value: String = 2;
     */
    String = 2,
    /**
     * @generated from protobuf enum value: JSON = 3;
     */
    JSON = 3
}
/**
 * @generated from protobuf enum CustomDataType
 */
export declare enum CustomDataType {
    /**
     * @generated from protobuf enum value: Bool = 0;
     */
    Bool = 0,
    /**
     * @generated from protobuf enum value: Num = 1;
     */
    Num = 1,
    /**
     * @generated from protobuf enum value: Str = 2;
     */
    Str = 2,
    /**
     * @generated from protobuf enum value: Null = 3;
     */
    Null = 3
}
declare class NullableString$Type extends MessageType<NullableString> {
    constructor();
    create(value?: PartialMessage<NullableString>): NullableString;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NullableString): NullableString;
    internalBinaryWrite(message: NullableString, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message NullableString
 */
export declare const NullableString: NullableString$Type;
declare class NullableDouble$Type extends MessageType<NullableDouble> {
    constructor();
    create(value?: PartialMessage<NullableDouble>): NullableDouble;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NullableDouble): NullableDouble;
    internalBinaryWrite(message: NullableDouble, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message NullableDouble
 */
export declare const NullableDouble: NullableDouble$Type;
declare class CustomDataValue$Type extends MessageType<CustomDataValue> {
    constructor();
    create(value?: PartialMessage<CustomDataValue>): CustomDataValue;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CustomDataValue): CustomDataValue;
    internalBinaryWrite(message: CustomDataValue, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message CustomDataValue
 */
export declare const CustomDataValue: CustomDataValue$Type;
declare class NullableCustomData$Type extends MessageType<NullableCustomData> {
    constructor();
    create(value?: PartialMessage<NullableCustomData>): NullableCustomData;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NullableCustomData): NullableCustomData;
    private binaryReadMap1;
    internalBinaryWrite(message: NullableCustomData, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message NullableCustomData
 */
export declare const NullableCustomData: NullableCustomData$Type;
declare class VariableForUserParams_PB$Type extends MessageType<VariableForUserParams_PB> {
    constructor();
    create(value?: PartialMessage<VariableForUserParams_PB>): VariableForUserParams_PB;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: VariableForUserParams_PB): VariableForUserParams_PB;
    internalBinaryWrite(message: VariableForUserParams_PB, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message VariableForUserParams_PB
 */
export declare const VariableForUserParams_PB: VariableForUserParams_PB$Type;
declare class DVCUser_PB$Type extends MessageType<DVCUser_PB> {
    constructor();
    create(value?: PartialMessage<DVCUser_PB>): DVCUser_PB;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DVCUser_PB): DVCUser_PB;
    internalBinaryWrite(message: DVCUser_PB, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message DVCUser_PB
 */
export declare const DVCUser_PB: DVCUser_PB$Type;
declare class SDKVariable_PB$Type extends MessageType<SDKVariable_PB> {
    constructor();
    create(value?: PartialMessage<SDKVariable_PB>): SDKVariable_PB;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SDKVariable_PB): SDKVariable_PB;
    internalBinaryWrite(message: SDKVariable_PB, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message SDKVariable_PB
 */
export declare const SDKVariable_PB: SDKVariable_PB$Type;
export {};
