import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useVariable } from '@devcycle/devcycle-react-sdk'

const Home: NextPage = () => {
    const variableKey = 'feature-release'
    const variableKeyString = 'variable-key-string'
    const variableKeyNumber = 'variable-key-number'
    const variableKeyBoolean = 'variable-key-boolean'
    const variableKeyJson = 'json-key-string'


    const variable = useVariable( variableKey, true)
    const variableString = useVariable( variableKeyString, 'pink')
    const variableNumber = useVariable( variableKeyNumber, 100)
    const variableBoolean = useVariable( variableKeyBoolean, true)
    const variableJson = useVariable( 'json-key-string', {'jsonStringKey1':'json string value 1'})


    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>

                <p className={styles.description}>
                    Get started by editing{' '}
                    <code className={styles.code}>pages/index.tsx</code>
                    and
                    <code className={styles.code}>_app.tsx</code>
                </p>

                <div className={styles.description}>
                    <span> Your default variable feature-release = {variable?.value ? 'ON' : 'OFF'} </span>
                    <div>
                        Your variable variableString = {variableString.value}
                    </div>
                    <div>
                        Your variable variableNumber = {variableNumber.value}
                    </div>
                    <div>
                        Your variable variableBoolean = {variableBoolean.value ? 'ON' : 'OFF'}
                    </div>
                    <div>
                        Your variable variableJson = {JSON.stringify(variableJson.value)}
                    </div>
                
                </div>



                

                <div className={styles.grid}>
                    <a href="https://nextjs.org/docs" className={styles.card}>
                        <h2>Documentation &rarr;</h2>
                        <p>Find in-depth information about Next.js features and API.</p>
                    </a>

                    <a href="https://nextjs.org/learn" className={styles.card}>
                        <h2>Learn &rarr;</h2>
                        <p>Learn about Next.js in an interactive course with quizzes!</p>
                    </a>

                    <a
                        href="https://github.com/vercel/next.js/tree/master/examples"
                        className={styles.card}
                    >
                        <h2>Examples &rarr;</h2>
                        <p>Discover and deploy boilerplate example Next.js projects.</p>
                    </a>

                    <a
                        href={'https://vercel.com/new?utm_source=create-next-app&' +
                            'utm_medium=default-template&utm_campaign=create-next-app'}
                        className={styles.card}
                    >
                        <h2>Deploy &rarr;</h2>
                        <p>
                            Instantly deploy your Next.js site to a public URL with Vercel.
                        </p>
                    </a>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href={'https://vercel.com?utm_source=create-next-app&utm_medium=defa' +
                        'ult-template&utm_campaign=create-next-app'}
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
                    </span>
                </a>
            </footer>
        </div>
    )
}

export default Home
