// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { CustomDataValue } from "./CustomDataValue";

export class ClientCustomData_PB {
  static encode(message: ClientCustomData_PB, writer: Writer): void {
    const value = message.value;
    if (value !== null) {
      const valueKeys = value.keys();
      for (let i: i32 = 0; i < valueKeys.length; ++i) {
        const valueKey = valueKeys[i];
        writer.uint32(10);
        writer.fork();
        writer.uint32(10);
        writer.string(valueKey);
        writer.uint32(18);
        writer.fork();
        CustomDataValue.encode(value.get(valueKey), writer);
        writer.ldelim();
        writer.ldelim();
      }
    }
  }

  static decode(reader: Reader, length: i32): ClientCustomData_PB {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ClientCustomData_PB();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          let valueKey: string = "";
          let valueValue: CustomDataValue | null = null;
          let valueHasKey: bool = false;
          let valueHasValue: bool = false;
          for (
            const end: usize = reader.ptr + reader.uint32();
            reader.ptr < end;

          ) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
              case 1:
                valueKey = reader.string();
                valueHasKey = true;
                break;

              case 2:
                valueValue = CustomDataValue.decode(reader, reader.uint32());
                valueHasValue = true;
                break;

              default:
                reader.skipType(tag & 7);
                break;
            }
            if (message.value === null) {
              message.value = new Map<string, CustomDataValue>();
            }
            const value = message.value;
            if (
              value !== null &&
              valueHasKey &&
              valueHasValue &&
              valueValue !== null
            ) {
              value.set(valueKey, valueValue);
            }
          }
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  value: Map<string, CustomDataValue>;

  constructor(value: Map<string, CustomDataValue> = new Map()) {
    this.value = value;
  }
}

export function encodeClientCustomData_PB(
  message: ClientCustomData_PB
): Uint8Array {
  return Protobuf.encode(message, ClientCustomData_PB.encode);
}

export function decodeClientCustomData_PB(
  buffer: Uint8Array
): ClientCustomData_PB {
  return Protobuf.decode<ClientCustomData_PB>(
    buffer,
    ClientCustomData_PB.decode
  );
}
