// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v5.29.3

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class EvalReason_PB {
  static encode(message: EvalReason_PB, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.reason);

    writer.uint32(18);
    writer.string(message.details);
  }

  static decode(reader: Reader, length: i32): EvalReason_PB {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new EvalReason_PB();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.reason = reader.string();
          break;

        case 2:
          message.details = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  reason: string;
  details: string;

  constructor(reason: string = "", details: string = "") {
    this.reason = reason;
    this.details = details;
  }
}

export function encodeEvalReason_PB(message: EvalReason_PB): Uint8Array {
  return Protobuf.encode(message, EvalReason_PB.encode);
}

export function decodeEvalReason_PB(buffer: Uint8Array): EvalReason_PB {
  return Protobuf.decode<EvalReason_PB>(buffer, EvalReason_PB.decode);
}
