// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

import { Writer, Reader, Protobuf } from "as-proto/assembly";

@unmanaged
export class NullableString {
  static encode(message: NullableString, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.value);

    writer.uint32(16);
    writer.bool(message.isNull);
  }

  static decode(reader: Reader, length: i32): NullableString {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new NullableString();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.value = reader.string();
          break;

        case 2:
          message.isNull = reader.bool();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  value: string;
  isNull: bool;

  constructor(value: string = "", isNull: bool = false) {
    this.value = value;
    this.isNull = isNull;
  }

  free(): void {
      heap.free(changetype<usize>(this))
  }
}

export function encodeNullableString(message: NullableString): Uint8Array {
  return Protobuf.encode(message, NullableString.encode);
}

export function decodeNullableString(buffer: Uint8Array): NullableString {
  return Protobuf.decode<NullableString>(buffer, NullableString.decode);
}
