// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v5.29.3

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { NullableString } from "./NullableString";
import { VariableType_PB } from "./VariableType_PB";

export class SDKVariableWithEval_Flat_PB {
  static encode(message: SDKVariableWithEval_Flat_PB, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.id);

    writer.uint32(16);
    writer.int32(message.type);

    writer.uint32(26);
    writer.string(message.key);

    writer.uint32(32);
    writer.bool(message.boolValue);

    writer.uint32(41);
    writer.double(message.doubleValue);

    writer.uint32(50);
    writer.string(message.stringValue);

    const evalReason = message.evalReason;
    if (evalReason !== null) {
      writer.uint32(58);
      writer.fork();
      NullableString.encode(evalReason, writer);
      writer.ldelim();
    }

    const feature = message.feature;
    if (feature !== null) {
      writer.uint32(66);
      writer.fork();
      NullableString.encode(feature, writer);
      writer.ldelim();
    }

    writer.uint32(74);
    writer.string(message.evalReason2);

    writer.uint32(82);
    writer.string(message.evalDetails);

    writer.uint32(90);
    writer.string(message.evalTargetId);
  }

  static decode(reader: Reader, length: i32): SDKVariableWithEval_Flat_PB {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new SDKVariableWithEval_Flat_PB();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.id = reader.string();
          break;

        case 2:
          message.type = reader.int32();
          break;

        case 3:
          message.key = reader.string();
          break;

        case 4:
          message.boolValue = reader.bool();
          break;

        case 5:
          message.doubleValue = reader.double();
          break;

        case 6:
          message.stringValue = reader.string();
          break;

        case 7:
          message.evalReason = NullableString.decode(reader, reader.uint32());
          break;

        case 8:
          message.feature = NullableString.decode(reader, reader.uint32());
          break;

        case 9:
          message.evalReason2 = reader.string();
          break;

        case 10:
          message.evalDetails = reader.string();
          break;

        case 11:
          message.evalTargetId = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  id: string;
  type: VariableType_PB;
  key: string;
  boolValue: bool;
  doubleValue: f64;
  stringValue: string;
  evalReason: NullableString | null;
  feature: NullableString | null;
  evalReason2: string;
  evalDetails: string;
  evalTargetId: string;

  constructor(
    id: string = "",
    type: VariableType_PB = 0,
    key: string = "",
    boolValue: bool = false,
    doubleValue: f64 = 0.0,
    stringValue: string = "",
    evalReason: NullableString | null = null,
    feature: NullableString | null = null,
    evalReason2: string = "",
    evalDetails: string = "",
    evalTargetId: string = ""
  ) {
    this.id = id;
    this.type = type;
    this.key = key;
    this.boolValue = boolValue;
    this.doubleValue = doubleValue;
    this.stringValue = stringValue;
    this.evalReason = evalReason;
    this.feature = feature;
    this.evalReason2 = evalReason2;
    this.evalDetails = evalDetails;
    this.evalTargetId = evalTargetId;
  }
}

export function encodeSDKVariableWithEval_Flat_PB(
  message: SDKVariableWithEval_Flat_PB
): Uint8Array {
  return Protobuf.encode(message, SDKVariableWithEval_Flat_PB.encode);
}

export function decodeSDKVariableWithEval_Flat_PB(
  buffer: Uint8Array
): SDKVariableWithEval_Flat_PB {
  return Protobuf.decode<SDKVariableWithEval_Flat_PB>(
    buffer,
    SDKVariableWithEval_Flat_PB.decode
  );
}
