// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v5.29.3

import { Writer, Reader, Protobuf } from "as-proto/assembly";
import { NullableString } from "./NullableString";
import { EvalReason_PB } from "./EvalReason_PB";
import { VariableType_PB } from "./VariableType_PB";

export class SDKVariableWithEval_PB {
  static encode(message: SDKVariableWithEval_PB, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.id);

    writer.uint32(16);
    writer.int32(message.type);

    writer.uint32(26);
    writer.string(message.key);

    writer.uint32(32);
    writer.bool(message.boolValue);

    writer.uint32(41);
    writer.double(message.doubleValue);

    writer.uint32(50);
    writer.string(message.stringValue);

    const feature = message.feature;
    if (feature !== null) {
      writer.uint32(66);
      writer.fork();
      NullableString.encode(feature, writer);
      writer.ldelim();
    }

    const eval = message.eval;
    if (eval !== null) {
      writer.uint32(74);
      writer.fork();
      EvalReason_PB.encode(eval, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): SDKVariableWithEval_PB {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new SDKVariableWithEval_PB();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.id = reader.string();
          break;

        case 2:
          message.type = reader.int32();
          break;

        case 3:
          message.key = reader.string();
          break;

        case 4:
          message.boolValue = reader.bool();
          break;

        case 5:
          message.doubleValue = reader.double();
          break;

        case 6:
          message.stringValue = reader.string();
          break;

        case 8:
          message.feature = NullableString.decode(reader, reader.uint32());
          break;

        case 9:
          message.eval = EvalReason_PB.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  id: string;
  type: VariableType_PB;
  key: string;
  boolValue: bool;
  doubleValue: f64;
  stringValue: string;
  feature: NullableString | null;
  eval: EvalReason_PB | null;

  constructor(
    id: string = "",
    type: VariableType_PB = 0,
    key: string = "",
    boolValue: bool = false,
    doubleValue: f64 = 0.0,
    stringValue: string = "",
    feature: NullableString | null = null,
    eval: EvalReason_PB | null = null
  ) {
    this.id = id;
    this.type = type;
    this.key = key;
    this.boolValue = boolValue;
    this.doubleValue = doubleValue;
    this.stringValue = stringValue;
    this.feature = feature;
    this.eval = eval;
  }
}

export function encodeSDKVariableWithEval_PB(
  message: SDKVariableWithEval_PB
): Uint8Array {
  return Protobuf.encode(message, SDKVariableWithEval_PB.encode);
}

export function decodeSDKVariableWithEval_PB(
  buffer: Uint8Array
): SDKVariableWithEval_PB {
  return Protobuf.decode<SDKVariableWithEval_PB>(
    buffer,
    SDKVariableWithEval_PB.decode
  );
}
