// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.23.4

export enum VariableType_PB {
  Boolean = 0,
  Number = 1,
  String = 2,
  JSON = 3,
}
