// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.2.0
//   protoc        v3.21.12

export enum VariableType_PB {
  Boolean = 0,
  Number = 1,
  String = 2,
  JSON = 3,
}
