import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useVariable } from '@devcycle/react-client-sdk'
import { getServerSideDevCycle } from '@devcycle/nextjs-sdk/pages'

const Home: NextPage = () => {
    const variableKey = 'test-featre'
    const variableKeyString = 'variable-key-string'
    const variableKeyNumber = 'variable-key-number'
    const variableKeyBoolean = 'variable-key-boolean'
    const variableKeyJsonString = 'variable-json-key-string'

    const variable = useVariable(variableKey, false)
    const variableString = useVariable(variableKeyString, 'default')
    const variableNumber = useVariable(variableKeyNumber, 100)
    const variableBoolean = useVariable(variableKeyBoolean, true)
    const variableJsonString = useVariable(variableKeyJsonString, {
        jsonStringKeyDefault: 'json string default',
    })
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>

                <p className={styles.description}>
                    Get started by editing{' '}
                    <code className={styles.code}>pages/index.tsx</code>
                    and
                    <code className={styles.code}>_app.tsx</code>
                </p>

                <div className={styles.description}>
                    <div>
                        <div>
                            <span>React next js</span>
                        </div>
                        <div>
                            <span>
                                variable feature-release ={' '}
                                {JSON.stringify(variable?.value)}{' '}
                            </span>
                        </div>
                        <div>
                            <span>
                                variable variable-key-string ={' '}
                                {JSON.stringify(variableString?.value)}{' '}
                            </span>
                        </div>
                        <div>
                            <span>
                                variable variable-key-number ={' '}
                                {JSON.stringify(variableNumber?.value)}{' '}
                            </span>
                        </div>
                        <div>
                            <span>
                                variable variable-key-boolean ={' '}
                                {JSON.stringify(variableBoolean?.value)}
                            </span>
                        </div>
                        <div>
                            <span>
                                variable variable-json-key-string ={' '}
                                {JSON.stringify(variableJsonString?.value)}{' '}
                            </span>
                        </div>
                    </div>
                </div>

                <div className={styles.grid}>
                    <a href="https://nextjs.org/docs" className={styles.card}>
                        <h2>Documentation &rarr;</h2>
                        <p>
                            Find in-depth information about Next.js features and
                            API.
                        </p>
                    </a>

                    <a href="https://nextjs.org/learn" className={styles.card}>
                        <h2>Learn &rarr;</h2>
                        <p>
                            Learn about Next.js in an interactive course with
                            quizzes!
                        </p>
                    </a>

                    <a
                        href="https://github.com/vercel/next.js/tree/master/examples"
                        className={styles.card}
                    >
                        <h2>Examples &rarr;</h2>
                        <p>
                            Discover and deploy boilerplate example Next.js
                            projects.
                        </p>
                    </a>

                    <a
                        href={
                            'https://vercel.com/new?utm_source=create-next-app&' +
                            'utm_medium=default-template&utm_campaign=create-next-app'
                        }
                        className={styles.card}
                    >
                        <h2>Deploy &rarr;</h2>
                        <p>
                            Instantly deploy your Next.js site to a public URL
                            with Vercel.
                        </p>
                    </a>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href={
                        'https://vercel.com?utm_source=create-next-app&utm_medium=defa' +
                        'ult-template&utm_campaign=create-next-app'
                    }
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
    return {
        props: {
            ...(await getServerSideDevCycle(
                process.env.NEXT_PUBLIC_DEVCYCLE_CLIENT_SDK_KEY || '',
                {
                    user_id: 'server-user',
                },
                context,
            )),
        },
    }
}

export default Home
