name: Nx Affected CI
on:
    pull_request:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [22.12]
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Enable Corepack
              run: corepack enable
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - run: git fetch origin main
            - run: yarn --immutable
            - run: yarn affected:lint --parallel=4
            - run: yarn prettier --check .
              name: Prettier
            - name: Run Affected Tests
              shell: bash
              run: |
                yarn nx build shared-bucketing-test-data
                yarn affected:test --parallel=4
