name: Nx Affected E2E
on:
    pull_request:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [22.x]
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - run: git fetch origin main
            - run: yarn --immutable
            - name: Install Playwright Browsers
              shell: bash
              run: yarn playwright install --with-deps
            - name: Run Affected E2E Tests
              shell: bash
              run: yarn affected:e2e
              env:
                E2E_NEXTJS_SERVER_KEY: ${{ secrets.E2E_NEXTJS_SERVER_KEY }}
                NEXT_PUBLIC_E2E_NEXTJS_KEY: ${{ secrets.NEXT_PUBLIC_E2E_NEXTJS_CLIENT_KEY }}
                NEXT_PUBLIC_E2E_NEXTJS_CLIENT_KEY: ${{ secrets.NEXT_PUBLIC_E2E_NEXTJS_CLIENT_KEY }}
                DVC_E2E_SERVER_SDK_KEY: ${{ secrets.DVC_E2E_SERVER_SDK_KEY }}
            - name: Upload Playwright Report
              if: always()
              uses: actions/upload-artifact@v2
              with:
                  name: playwright-report
                  path: dist/.playwright/e2e/
