name: Nx Affected E2E
on:
    pull_request:
        branches: [main]
jobs:
    build:
        runs-on: ubicloud-standard-4
        permissions:
          contents: read
          id-token: write
          pull-requests: write
          issues: write
        strategy:
            matrix:
                node-version: [22.12]
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Enable Corepack
              run: corepack enable
            - name: Set Secrets
              uses: DevCycleHQ/aws-secrets-action@main
              with:
                secrets_map: '{"E2E_NEXTJS_SERVER_KEY":"DEVCYCLE_GITHUB_js-sdks_E2E_NEXTJS_SERVER_KEY", "NEXT_PUBLIC_E2E_NEXTJS_CLIENT_KEY": "DEVCYCLE_GITHUB_js-sdks_NEXT_PUBLIC_E2E_NEXTJS_CLIENT_KEY", "DVC_E2E_SERVER_SDK_KEY": "DEVCYCLE_GITHUB_js-sdks_DVC_E2E_SERVER_SDK_KEY"}'
                aws_account_id: '134377926370'
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - run: git fetch origin main
            - run: yarn --immutable
            - name: Install Playwright Browsers
              shell: bash
              run: yarn playwright install --with-deps
            - name: Run Affected E2E Tests
              shell: bash
              run: yarn affected:e2e
            - name: Upload Playwright Report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: playwright-report
                  path: dist/.playwright/e2e/
