name: Nx Affected CI
on:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: git fetch origin main
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-yarn-cache
        with:
          path: |
            .yarn/cache
            .yarn/unplugged
            node_modules/.cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: yarn --immutable
      - run: yarn affected:lint
      - name: Run Affected Tests
        shell: bash
        run: yarn affected:test
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: DevCycleHQ
          repo: test-harness
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workflow_file_name: config.yml
          ref: main
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true