name: Run Test Harness
permissions:
    contents: read
on:
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on:
            labels: ubicloud-standard-16
        strategy:
            matrix:
                node-version: [22.12]
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Enable Corepack
              run: corepack enable
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - name: Run Yarn
              run: yarn --immutable
            - name: Check affected projects
              run: |
                  if yarn nx print-affected --base=origin/main --select=projects | grep -E '(^nodejs|[^-]nodejs)'; then
                    echo "TRIGGER_NODEJS_TEST_HARNESS=true" >> $GITHUB_ENV
                  fi
            - uses: DevCycleHQ/test-harness@main
              if: contains(env.TRIGGER_NODEJS_TEST_HARNESS, 'true')
              with:
                  sdks-to-test: nodejs,of-nodejs
                  sdk-github-sha: ${{github.event.pull_request.head.sha}}
                  github-token: ${{ secrets.AUTOMATION_USER_TOKEN }}
                    sdk-capabilities: '{ "NodeJS":["edgeDB", "cloud", "lastModifiedHeader", "bootstrapping", "sdkConfigEvent", "clientUUID", "v2Config", "clientCustomData", "variablesFeatureId", "cloudEvalReason", "evalReason"], "OF_NodeJS": ["edgeDB", "cloud", "lastModifiedHeader", "sdkConfigEvent", "clientUUID", "v2Config", "sdkPlatform", "variablesFeatureId","evalReason"]}'
