name: Run Test Harness
on:
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on:
            labels: ubuntu-latest-4-core
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Install protoc for protobuf compilation
              run: sudo apt-get install -y protobuf-compiler
            - name: Run Yarn
              run: yarn --immutable
            - name: Check affected projects
              run: |
                  if yarn nx print-affected --base=origin/main --select=projects | grep -E '(^nodejs|[^-]nodejs)'; then
                    echo "TRIGGER_NODEJS_TEST_HARNESS=true" >> $GITHUB_ENV
                  fi
                  if yarn nx print-affected --base=origin/main --select=projects | grep -E '(^openfeature-nodejs-provider)'; then
                    echo "TRIGGER_NODEJS_OF_TEST_HARNESS=true" >> $GITHUB_ENV
                  fi
            - uses: DevCycleHQ/test-harness@main
              if: contains(env.TRIGGER_NODEJS_TEST_HARNESS, 'true') && !contains(env.TRIGGER_NODEJS_OF_TEST_HARNESS, 'true')
              with:
                  sdks-to-test: nodejs
                  sdk-github-sha: ${{github.event.pull_request.head.sha}}
                  github-token: ${{ secrets.TEST_HARNESS_GH_SECRET }}
            - uses: DevCycleHQ/test-harness@main
              if: !contains(env.TRIGGER_NODEJS_TEST_HARNESS , 'true') && contains(env.TRIGGER_NODEJS_OF_TEST_HARNESS, 'true')
              with:
                  sdks-to-test: of-nodejs
                  sdk-github-sha: ${{github.event.pull_request.head.sha}}
                  github-token: ${{ secrets.TEST_HARNESS_GH_SECRET }}
            - uses: DevCycleHQ/test-harness@main
              if: contains(env.TRIGGER_NODEJS_TEST_HARNESS, 'true') && contains(env.TRIGGER_NODEJS_OF_TEST_HARNESS, 'true')
              with:
                  sdks-to-test: nodejs,of-nodejs
                  sdk-github-sha: ${{github.event.pull_request.head.sha}}
                  github-token: ${{ secrets.TEST_HARNESS_GH_SECRET }}
