name: Run Test Harness
on:
  pull_request:
    branches: [main]
    paths:
      - 'sdk/nodejs/*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: DevCycleHQ
          repo: test-harness
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workflow_file_name: config.yml
          ref: main
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
          client_payload: '{ "sha": "${{ github.event.pull_request.head.sha }}", "sdk": "nodejs" }'
